// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
export {};
//需要替换@vue/runtime-core为vue 保证使用第三方组件库时有属性和方法提示
declare module "vue" {
  export interface GlobalComponents {
    ElButton: typeof import("element-plus/es")["ElButton"];
    ElDelete: typeof import("element-plus/es")["ElDelete"];
    ElDialog: typeof import("element-plus/es")["ElDialog"];
    ElEdit: typeof import("element-plus/es")["ElEdit"];
    ElIconDelete: typeof import("@element-plus/icons-vue")["Delete"];
    ElIconEdit: typeof import("@element-plus/icons-vue")["Edit"];
    ElIconSearch: typeof import("@element-plus/icons-vue")["Search"];
    ElIconShare: typeof import("@element-plus/icons-vue")["Share"];
    ElOption: typeof import("element-plus/es")["ElOption"];
    ElSearch: typeof import("element-plus/es")["ElSearch"];
    ElSelect: typeof import("element-plus/es")["ElSelect"];
    ElShare: typeof import("element-plus/es")["ElShare"];
    HelloWorld: typeof import("./components/HelloWorld.vue")["default"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
  }
}
